name:                max-ones-ga
version:             0.1.0.0
github:              "Eric-Arellano/haskell-max-ones-genetic-algorithm"
license:             BSD3
author:              "Eric Arellano"
maintainer:          "ecarell1@asu.edu"
copyright:           "2019 Eric Arellano"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Eric-Arellano/haskell-max-ones-genetic-algorithm#readme>

dependencies:
- base >= 4.7 && < 5
- random
- mtl
- ConfigFile
- QuickCheck

library:
  source-dirs: src

executables:
  max-ones-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options: &ghc_options
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    dependencies:
    - max-ones-ga

tests:
  max-ones-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options: *ghc_options
    dependencies:
    - max-ones-ga
